define sfu_fwd::firewallrule(
  $fprotocol  = '',
  $fsport     = '',
  $fdport     = '',
  $fsource    = '10.1.1.1/32',
  $fdest,
  $fsequence  = '',
  $faction    = '',
  $fname      = $title,
  $fchain     = '',
  $fjump      = '',
  $finiface   = '',
  $foutiface  = '',
  $ftable     = '',
  $fstate     = '',
  $ftcpflags  = '',
) {
  firewall { "${fname}":
    proto        => '$fprotocol',
    sport        => '$fsport',
    dport        => '$fsport',
    source       => $fsource,
    destination  => $fdest,
    action       => $faction,
    provider     => 'iptables',
    chain        => '$fchain',
    jump         => '$fjump',
    iniface      => '$finiface',
    outiface     => '$foutiface',
    table        => '$ftable',
    state        => '$fstate',
    tcp_flags    => '$ftcpflags',
  }
}
